### ISSUE TITLE
CrazyPanda.UnityCore.Utils

### ISSUE THREAD

**Issue by SandersAlex** [CrazyPandaLimited/SimplePromises#2]
Здравстуйте.

Отсутствует библиотека CrazyPanda.UnityCore.Utils и невозможно дальше работать с SimplePromises

Нет кода для ValidateEmptyString и CheckArgumentForNull

**Comment by artificialpancakes** [comment]
Привет. Поставь в проект ещё UtilsCollectionSystem. https://github.com/CrazyPandaLimited/UtilsCollectionSystem

**Comment by SandersAlex** [comment]
> Привет. Поставь в проект ещё UtilsCollectionSystem. https://github.com/CrazyPandaLimited/UtilsCollectionSystem

Благодарю. А может на него указать ссылку в readme, чтобы народ не спршивал глупых вопросов? :[
